server:
  port: 10002  #slave
spring:
  application:
    name: member-service
eureka:
  client:
    #向注册中心注册自己，此处默认为true，可以不用加的
    register-with-eureka: true
    #让注册中心发现自己，默认也为true，可以不用加的
    fetch-registry: true
    #设置服务注册中心的URL，注册中心已经设置过了，直接去注册中心查看即可
    service-url:
      default-zone: http://localhost:8761/eureka/   #eureka服务器地址